import Head from 'next/head';
import Navigation from './Navigation.js';

import styles from '../styles/Layout.module.css';


export default function Layout({ content }) {
  let header =
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
    </div>;

  let footer =
    <div className={styles.footer}>
      <div className={styles.footer_text}>Cliff Yang</div>
    </div>;

  let page =
    <div className={styles.page}>
      {content}
    </div>;

  return (<div>
    {header}
    <Navigation />
    {page}
    {footer}
  </div>)
}
